### ISSUE TITLE
Servere Lag when applying patch

### ISSUE THREAD

**Issue by KingomKeyx86** [aldehir/ut2004-patches#13]
when i enter the game with this patch i get severe frame drops in ut2004. i did install it on a previous installation and it ran well.
i tried Uninstalling and reinstalling ut2004 and updating it to the latest version and then applying it, didn't work. but without the patch it runs fine without severe frame drops. tested my graphics driver if it was the problem, didn't make an impact. i'm not sure on how i ran it the first time.

**Comment by aldehir** [comment]
By severe frame drops do you mean from 200 to 30, or from 200 to 150? The default mouse input mode `directinput` adds frame drops with increased mouse activity. Switching to `rawinputbuffer` will resolve this, you can use `setmouseinput rawinputbuffer` to do that.

Otherwise, I suggest you back up your `UT2004.ini`---rename it to something like `UT2004.ini.bak`---and then run UT2004. If the drops persist, then we can rule out a configuration issue.

Did you reinstall your OS between the time it was first working and now?

**Comment by KingomKeyx86** [comment]
no i didn't reinstall the OS during when i had ut2004. the game is able to run full speed without the patch just fine. the problem that i'm noticing is that whenever i ran the game with the latest patch from this github page it suddenly impacted the games performances to about the 10-20 range. i'm using a laptop to run this game btw so its just up to 60hz for my monitor. the files that make up the patch that u made i backed up (from my base installation of ut2k4).

**Comment by KingomKeyx86** [comment]
[Update]
Managed to find the culprit. it was my settings. with ReduceMouseLag set to false and other tweaks to the .ini, its working smoothly. i had to reinstall just to get a fresh game install for things to work out properly. thanks for your help and time.

**Comment by aldehir** [comment]
I'm glad you got it working.
